[package]
name = "nix-du"
version = "0.3.4"
authors = ["Symphorien Gibol <symphorien+git@xlumurb.eu>"]
license = "LGPL-3.0"
edition = "2018"

# otherwise we get an unhelpful panic unwind when a c++ execption is raised.
[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"

[build-dependencies]
cc = "1.0"
pkg-config = "0.3"

[dependencies]
petgraph = "0.5"
fixedbitset = "0.2"
memchr = "2"
# output
humansize = "1"
# input
human-size = "0.4"
palette = "0.5"
walkdir = "2"
enum-map = "0.6"

[dependencies.clap]
version = "2"
features = ["suggestions", "color", "wrap_help"]

[dev-dependencies]
rand = "0.8"
cli_test_dir = "0.1"
regex = "1"
