name: "Test"
on:
  pull_request:
  push:
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.5.0
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-build test.nix
  # spurious failures due to https://github.com/kolloch/crate2nix/issues/263
  mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2.5.0
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-build test.nix
